version: '3'
services:
  web:
    build: apache
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/exemplo.lan.conf:/etc/apache2/sites-enabled/exemplo.lan.conf
      - ./apache/exemplo.lan.pem:/etc/ssl/certs/exemplo.lan.pem
      - ./apache/exemplo.lan.key:/etc/ssl/certs/exemplo.lan.key
      - ./apache/a22davidcr.giize.com.pem:/etc/ssl/certs/a22oscarnm.loseyourip.com.pem
      - ./apache/a22davidcr.giize.com.key:/etc/ssl/private/a22oscarnm.loseyourip.com.key